### ISSUE TITLE
option --env does not exist.

### ISSUE THREAD

**Issue by michaelpporter** [terminus-plugin-project/terminus-site-status-plugin#2]
I am running Terminus 1.4.0 and the latest site status plugin. when I run the example script I get an error.

terminus site:status --env=dev

  [Symfony\Component\Console\Exception\RuntimeException]
  The "--env" option does not exist.

site:status [--team] [--owner [OWNER]] [--org [ORG]] [--name [NAME]] [--format [FORMAT]] [--fields [FIELDS]] [--field [FIELD]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-y|--yes] [--] <command>

**Comment by uberhacker** [comment]
Hey @michaelpporter: Thank you for the feedback.  That switch option is no longer available in the 1.x release of Terminus.  The concept of this plugin is to return the status of all site environments.  If you run the command without any options, that should provide you all the information you need.  You could use `terminus site:status --name=my-site-name` to filter for a specific site.

**Comment by uberhacker** [comment]
Fixed in #4.
